// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyHoatDongNgoaiKhoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725123053_TOH")]
    partial class TOH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.BanDoDanhMucHoatDong", b =>
                {
                    b.Property<int>("MaBanDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanDo"));

                    b.Property<int>("DanhMucHoatDongMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("HoatDongMaHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaHoatDong")
                        .HasColumnType("int");

                    b.HasKey("MaBanDo");

                    b.HasIndex("DanhMucHoatDongMaDanhMuc");

                    b.HasIndex("HoatDongMaHoatDong");

                    b.ToTable("BanDoDanhMucHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DangKyThamGia", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThaiDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiDangKyMaTrangThaiDangKy")
                        .HasColumnType("int");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHoatDong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TrangThaiDangKyMaTrangThaiDangKy");

                    b.ToTable("DangKyThamGias");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.Property<int>("MaHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoatDong"));

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungTaoMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiHoatDongMaTrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHoatDong");

                    b.HasIndex("NguoiDungTaoMaNguoiDung");

                    b.HasIndex("TrangThaiHoatDongMaTrangThai");

                    b.ToTable("HoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaiTroMaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("VaiTroMaVaiTro");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NhatKyThaoTac", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("NhatKyThaoTacs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", b =>
                {
                    b.Property<int>("MaTrangThaiDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThaiDangKy"));

                    b.Property<string>("TenTrangThaiDangKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrangThaiDangKy");

                    b.ToTable("TrangThaiDangKys");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThaiHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.BanDoDanhMucHoatDong", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", "DanhMucHoatDong")
                        .WithMany("DanhSachBanDo")
                        .HasForeignKey("DanhMucHoatDongMaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", "HoatDong")
                        .WithMany("DanhMucHoatDong")
                        .HasForeignKey("HoatDongMaHoatDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucHoatDong");

                    b.Navigation("HoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DangKyThamGia", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", "HoatDong")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaHoatDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", "TrangThaiDangKy")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("TrangThaiDangKyMaTrangThaiDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoatDong");

                    b.Navigation("NguoiDung");

                    b.Navigation("TrangThaiDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDungTao")
                        .WithMany()
                        .HasForeignKey("NguoiDungTaoMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", "TrangThaiHoatDong")
                        .WithMany("DanhSachHoatDong")
                        .HasForeignKey("TrangThaiHoatDongMaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDungTao");

                    b.Navigation("TrangThaiHoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", "VaiTro")
                        .WithMany("DanhSachNguoiDung")
                        .HasForeignKey("VaiTroMaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NhatKyThaoTac", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", b =>
                {
                    b.Navigation("DanhSachBanDo");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.Navigation("DanhMucHoatDong");

                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", b =>
                {
                    b.Navigation("DanhSachHoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", b =>
                {
                    b.Navigation("DanhSachNguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
