// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyHoatDongNgoaiKhoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250726015532_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.BanDoDanhMucHoatDong", b =>
                {
                    b.Property<int>("MaBanDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanDo"));

                    b.Property<int>("DanhMucHoatDongMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("HoatDongMaHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaHoatDong")
                        .HasColumnType("int");

                    b.HasKey("MaBanDo");

                    b.HasIndex("DanhMucHoatDongMaDanhMuc");

                    b.HasIndex("HoatDongMaHoatDong");

                    b.ToTable("BanDoDanhMucHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DangKyThamGia", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiDangKyMaTrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHoatDong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TrangThaiDangKyMaTrangThai");

                    b.ToTable("DangKyThamGias");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.Property<int>("MaHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoatDong"));

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungTaoMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThaiHoatDongMaTrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHoatDong");

                    b.HasIndex("NguoiDungTaoMaNguoiDung");

                    b.HasIndex("TrangThaiHoatDongMaTrangThai");

                    b.ToTable("HoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaiTroMaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("VaiTroMaVaiTro");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NhatKyThaoTac", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThaoTac")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("NhatKyThaoTacs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThaiDangKys");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThaiHoatDongs");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.BanDoDanhMucHoatDong", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", "DanhMucHoatDong")
                        .WithMany("DanhSachBanDo")
                        .HasForeignKey("DanhMucHoatDongMaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", "HoatDong")
                        .WithMany()
                        .HasForeignKey("HoatDongMaHoatDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucHoatDong");

                    b.Navigation("HoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DangKyThamGia", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", "HoatDong")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaHoatDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", "TrangThaiDangKy")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("TrangThaiDangKyMaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoatDong");

                    b.Navigation("NguoiDung");

                    b.Navigation("TrangThaiDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDungTao")
                        .WithMany()
                        .HasForeignKey("NguoiDungTaoMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", "TrangThaiHoatDong")
                        .WithMany("DanhSachHoatDong")
                        .HasForeignKey("TrangThaiHoatDongMaTrangThai");

                    b.Navigation("NguoiDungTao");

                    b.Navigation("TrangThaiHoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", "VaiTro")
                        .WithMany("DanhSachNguoiDung")
                        .HasForeignKey("VaiTroMaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NhatKyThaoTac", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.DanhMucHoatDong", b =>
                {
                    b.Navigation("DanhSachBanDo");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.HoatDong", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiDangKy", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.TrangThaiHoatDong", b =>
                {
                    b.Navigation("DanhSachHoatDong");
                });

            modelBuilder.Entity("QuanLyHoatDongNgoaiKhoa.Models.VaiTro", b =>
                {
                    b.Navigation("DanhSachNguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
